databases:
  - name: orka_db
    plan: free
    databaseName: orka_db
    user: orka

services:
  - type: web
    plan: free
    name: orka
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn orka.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: orka_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4