databases:
  - name: orkadb
    plan: Starter
    databaseName: orka
    user: orka

services:
  - type: web
    plan: free
    name: orka
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd server && python -m gunicorn server.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: orkadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4