# Generated by Django 4.2.13 on 2024-06-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0002_remove_project_created_at_remove_project_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='logo',
            new_name='client_img',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='updated_at',
        ),
    ]
