# Generated by Django 4.2.13 on 2024-07-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0003_rename_logo_client_client_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='updated_at',
        ),
    ]
