# Generated by Django 4.2.13 on 2024-06-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0003_project_productionneed_budgetitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
