# Generated by Django 4.2.13 on 2024-06-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0004_alter_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(),
        ),
    ]
