# Generated by Django 4.2.13 on 2024-07-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0004_remove_budgetitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='updated_at',
        ),
    ]
