# Generated by Django 4.2.13 on 2024-07-13 23:51

import datetime
from django.db import migrations, models
import orka.models.Project


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0005_remove_account_created_at_remove_account_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date.today, validators=[orka.models.Project.validate_deadline]),
        ),
    ]
