# Generated by Django 4.2.13 on 2024-06-13 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0005_alter_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='account',
            name='logo',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(default='Advertising', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
