# Generated by Django 4.2.13 on 2024-06-13 21:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0006_account_created_at_account_logo_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 13, 21, 34, 41, 57646)),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 13, 21, 34, 41, 57641)),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 13, 21, 34, 41, 57650)),
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 13, 21, 34, 41, 56754)),
        ),
        migrations.AddField(
            model_name='client',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 13, 21, 34, 41, 56764)),
        ),
        migrations.AddField(
            model_name='productionneed',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 13, 21, 34, 41, 57068)),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 13, 21, 34, 41, 57073)),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productionneed',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 13, 21, 34, 41, 57349)),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 13, 21, 34, 41, 57062)),
        ),
        migrations.CreateModel(
            name='UserProductionNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productionneed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orka.productionneed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orka.user')),
            ],
        ),
    ]
