# Generated by Django 4.2.13 on 2024-07-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0007_expense_task_remove_productionneed_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='logo',
        ),
    ]
