# Generated by Django 4.2.13 on 2024-07-23 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0008_remove_account_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
