# Generated by Django 4.2.13 on 2024-07-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0010_remove_expense_name_expense_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='deadline',
        ),
    ]
