# Generated by Django 4.2.13 on 2024-07-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orka', '0012_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.FloatField(default=0.0),
        ),
    ]
